### ISSUE TITLE
update hook

### ISSUE THREAD

**Issue by epubreader** [ladjs/mongoose-slug-plugin#14]
1. add an option to disable slug history field
2. add pre update and findOneUpdate hook, current validate hook only fire when save.
Thanks.

**Comment by niftylettuce** [comment]
PR welcome!

**Comment by DanielVip3** [comment]
#16 tried to make the first request, which I absolutely needed.
Waiting for a merge ;)

**Comment by niftylettuce** [comment]
v2.1.0 released to npm, thank you

**Comment by niftylettuce** [comment]
If you want to file another issue for point number two in your original issue, or open a PR, feel free to.
