### ISSUE TITLE
use of deprecated count()

### ISSUE THREAD

**Issue by mario-merino** [ladjs/mongoose-slug-plugin#3]
DeprecationWarning: collection.count is deprecated, and will be removed in a future version. Use collection.countDocuments or collection.estimatedDocumentCount instead

I tested just changing line 13 of index from:
`const count = await constructor.count(query);`
to:
`const count = await constructor.countDocuments(query);`
and it fixed the warning message (as per guidelines of mongoose here[https://mongoosejs.com/docs/deprecations.html](url)

**Comment by niftylettuce** [comment]
Please use `mongoose-slug-plugin` newest version `2.0.0`:

```sh
npm install mongoose-slug-plugin@latest
```

Versions older than `v2.0.0` have the following deprecation message now upon installation:

"If you upgrade to v2.0.0+ please ensure you are using Mongoose v5.2+ or greater"

Any issues please let me know.
