### ISSUE TITLE
The `str` argument was missing at getUniqueSlug

### ISSUE THREAD

**Issue by emrealparslan93** [ladjs/mongoose-slug-plugin#5]
Hello, I've been facing with an issue when I try to save documents which uses mongoose-slug-plugin.

I've set `alwaysUpdateSlug` options to false to avoid slug check on each save(), but it keeps trying to check the slug. 

Here is my plugin settings:
`ShopSchema.plugin(mongooseSlugPlugin, { tmpl: "<%=name.en%>", alwaysUpdateSlug: false });`

Here is the log: 
`Error: The `str` argument was missing
    at getUniqueSlug (/app/node_modules/mongoose-slug-plugin/index.js:8:29)`

I guess it's because I select fields when I get document from its collections and I don't select `slug` field because I don't need it. But plugin tries to check the slug field which is null at this point. 

How can I disable this plugin for doc.save() functions? Or is there a way to bypass it where I don't want this plugin to check document?

**Comment by niftylettuce** [comment]
PR welcome or if you can provide a repo with failing test case let me know

**Comment by tranduyhung** [comment]
I got the same error even though I didn't use `alwaysUpdateSlug` option or didn't provide any options.


```
const mongooseSlugPlugin = require('mongoose-slug-plugin');
const mongoosePaginatePlugin = require('mongoose-paginate-v2');

const mongoose = require('mongoose')

const Schema = mongoose.Schema

const postSchema = new mongoose.Schema({
  title: {
    type: String,
    required: true,
    minlength: 2,
    maxlength: 255
  },
  body: {
    type: String,
    required: true,
  },
  createdDate: {
    type: Date,
  },
  modifiedDate: {
    type: Date,
  },
})

let options = {
  tmpl: '<%=title%>'
}

postSchema.plugin(mongooseSlugPlugin, { options });
postSchema.plugin(mongoosePaginatePlugin);

const PostModel = mongoose.model('Post', postSchema)

exports.PostModel = PostModel
```
