### ISSUE TITLE
DeprecationWarning: Mongoose: the `isAsync` 

### ISSUE THREAD

**Issue by luluhoc** [ladjs/mongoose-slug-plugin#8]
(node:65186) DeprecationWarning: Mongoose: the `isAsync` option for custom validators is deprecated. Make your async validators return a promise instead: https://mongoosejs.com/docs/validation.html#async-custom-validators

**Comment by niftylettuce** [comment]
v2.0.2 has been released to npm with this fixed

```sh
npm install mongoose-slug-plugin@latest
```

or with yarn:

```sh
yarn add mongoose-slug-plugin@latest
```
